### ISSUE TITLE
Parse argument in `texorpdfstring` in file outline broken

### ISSUE THREAD

**Issue by natestemen** [overleaf/overleaf#1037]
## Steps to Reproduce

1. Open default template project
2. Paste `\section{Hello World: \texorpdfstring{$a + b = c$}{a + b = c}}` into project

## Expected Behaviour

The file outline should parse out whichever entry it can and display only one.

## Observed Behaviour

Both are displayed
<img width="263" alt="Screen Shot 2022-07-23 at 11 49 32 AM" src="https://user-images.githubusercontent.com/12703123/180600196-bc0bbc8d-0146-45c3-ad8d-ace70b2dc63a.png">

**Comment by AnessZurba** [comment]
Hi,
I see this was fixed in [LatexWorkshop](https://github.com/James-Yu/LaTeX-Workshop/pull/2909/commits/1da262846d0515accfd7c1579db5738575a715fe)

Seems like the same fix can be applied in overleaf. Specifically [here](https://github.com/overleaf/overleaf/blob/c90d01afa250171b368cdea40484848de98573e6/services/web/frontend/js/features/source-editor/utils/tree-operations/outline.ts#L77)

I can open a PR, but I don't think I will be able to fully test this out since I don't have it set up.

Is there anybody that can help us with this?

**Comment by das7pad** [comment]
Hi @natestemen!

Thank you for your feature request. @AnessZurba's PR  https://github.com/overleaf/overleaf/pull/1245 has been merged(thanks again!).

The change is live on overleaf.com and will be included in the upcoming Server Pro and Community Edition 5.2 release.

![image](https://github.com/user-attachments/assets/c0338c2d-a14b-41b4-aa10-a2c1203628df)

Greetings,
Jakob
