### ISSUE TITLE
Turn on link sharing results in "Loading..." message 

### ISSUE THREAD

**Issue by chschenk** [overleaf/overleaf#1160]
## Steps to Reproduce

1. Click on "Share" menu item
2. Click on "Turn on link sharing"

## Expected Behaviour
Two links to view/edit appear in the textboxes below

## Observed Behaviour
The content of the textboxes is just "Loading..." .

## Context
Trying to share a overleaf project by a link.

## Technical Info
Overleaf tries to call project/{{Project_ID}}/tokens which results in HTTP 500. In the logs i can see the following entry:
`Unsupported projection option: isOwner: { $eq: [ \"$owner_ref\", ObjectId('<OBJID>') ] }","name":"MongoServerError","stack":"MongoServerError: Unsupported projection option: isOwner: { $eq: [ \"$owner_ref\", ObjectId('<OBJID>') ] }\n    at Connection.onMessage (/overleaf/services/web/node_modules/mongodb/lib/cmap/connection.js:231:30)\n    at MessageStream.<anonymous> (/overleaf/services/web/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (node:events:514:28)\n    at MessageStream.emit (node:domain:489:12)\n    at processIncomingData (/overleaf/services/web/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/overleaf/services/web/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Writable.write (node:internal/streams/writable:337:10)\n    at Socket.ondata (node:internal/streams/readable:766:22)\n    at Socket.emit (node:events:514:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by chschenk** [comment]
I fixed the issue by updating my MongoDB Instance to 4.4.

**Comment by michaelvanhorn** [comment]
How did you upgrade MongoDB to 4.4? 

I try to follow 

https://github.com/overleaf/overleaf/wiki/Updating-Mongo-version

where it says to update the value of MONGO_IMAGE (I'm using the toolkit). But, it doesn't say where that value is kept. What file did you have to modify to update MongoDB?

**Comment by chschenk** [comment]
You set the value of MONGO_IMAGE in the file overleaf.rc

**Comment by michaelvanhorn** [comment]
Thank you, I have now successfully upgraded the MongoDB image.

---
Mike VanHorn
Senior Computer Systems Administrator
College of Engineering and Computer Science
Wright State University
265 Russ Engineering Center
937-775-5157
***@***.***

From: Christopher ***@***.***>
Reply-To: overleaf/overleaf ***@***.***>
Date: Monday, December 18, 2023 at 4:17 AM
To: overleaf/overleaf ***@***.***>
Cc: Mike VanHorn ***@***.***>, Comment ***@***.***>
Subject: Re: [overleaf/overleaf] Turn on link sharing results in "Loading..." message (Issue #1160)

You set the value of MONGO_IMAGE in the file overleaf. rc — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: <overleaf/overleaf/issues/1160/1859867975@ github. com>
ZjQcmQRYFpfptBannerStart
CAUTION: This Message Is From an External Sender
Exercise caution when opening attachments or clicking links.
ZjQcmQRYFpfptBannerEnd

You set the value of MONGO_IMAGE in the file overleaf.rc
