### ISSUE TITLE
Migrating data to new machine

### ISSUE THREAD

**Issue by jimading** [overleaf/overleaf#180]
is there a reliable method to move all data to a fresh installation on a different machine?

**Comment by sirgogo** [comment]
> Just Turn off SL on the old server, copy redis and mongo data to the new
server then turn SL on.

Hi, I know this thread is closed, but I was wondering if you could elaborate on how to backup redis / mongo data?

I am running sharelatex with something like this:
```
docker run -d --name shareredis redis:latest
docker run -d --name sharemongo mongo:latest
docker run -d -P -v ~/tex:/var/lib/sharelatex  --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --link sharemongo:mongo --link shareredis:redis ...
```
I think I should backup `~/tex/`, which I am guessing houses the sharelatex documents. 
But, how do I backup mongodb and redis, so that I can restore them later if/when I make a new container?

Thanks in advance for your help.
