### ISSUE TITLE
Upgrading to TexLive2015

### ISSUE THREAD

**Issue by skgadi** [overleaf/overleaf#360]
Hi,

I am not sure, if this is the correct place to raise this doubt.

I have working sharelatex setup. I installed TexLive 2015 on the same computer. Latexmk is still compiling with the previous version i.e. the default 2013 version which comes along with the Latexmk.

Please guide me how to upgrade my system to 2015.

Thanks.

**Comment by bonanza123** [comment]
See here https://github.com/sharelatex/sharelatex/wiki/Dependencies at the bottom for how to install texlive. Then you need to update the $PATH variable in all upstart-scripts (/etc/init/sharelatex*conf) to point to the 2015 installation.

**Comment by hulk1st** [comment]
Just for the record, doing so broke my ShareLaTeX installation. I installed ShareLaTeX while TeXlive 2014 was the latest version and meanwhile upgraded from 2014 to 2015. Since the symlinks were adapted after installation, 2015 was used without changing the path in the init scripts, as also confirmed in the latex compile output.

However, when I changed 2014 to 2015 in all the inits scripts, ShareLaTeX did not start properly anymore. Some projects showed at least the code which however did not compile, while many projects not even showed the .tex code but only the spinning loading symbol which spun forever.

Changing the path in the init scripts back to 2014 did not solve the problem. I solved it by re-running the 2014 install script and subsequently the 2015 install script, while keeping the paths in the init scripts to point towards 2014.

**Comment by das7pad** [comment]
Hello,

A lot has changed since 2015. The Docker based deployment greatly simplifies the dependency management and running Overleaf on premises. TeXLive 2024 is included in the latest version of Overleaf Community Edition or [Server Pro](https://www.overleaf.com/for/enterprises). Our Server Pro offering also sports the Sandboxed Compiles feature will grants you access to the same optimized TeXLive environment as used on overleaf.com, including access to historic TeXLive releases, going back to 2014.

Greetings,
Jakob
