### ISSUE TITLE
Integrate with texlive.js

### ISSUE THREAD

**Issue by manuels** [overleaf/overleaf#40]
Great to see that this editor is open source now!
I'm the developer of [texlive.js](https://github.com/manuels/texlive.js/), a port of the latex compiler to javascript, and would love to see ShareLaTeX work with texlive.js.
I'm afraid, I don't have the time to implement this feature myself, right now. But of course I would help anyone who starts coding on this with questions concerning texlive.js.

**Comment by aicioara** [comment]
Pinging this as I am curious how this conversation evolved over the past 2 years. I want to work on something similar, but since you guys are more familiar with the situation, I was wondering if anything better came up.

My plan is to manually port the core of LaTeX to JavaScript (no more emscripten) in an attempt to speed up the compilation process and actually make it usable for a project like ShareLatex.

Aiming this question at @jpallen and @manuels in particular, as I was reading your conversation here as well https://www.reddit.com/r/programming/comments/16vzbh/latex_ported_to_javascript/ . Also any thoughts about my plan would be greatly appreciated

**Comment by manuels** [comment]
Hi aicioara,

porting Latex to JS by hand is an ambitious plan. I doubt that the result would be faster than emscripten. (emscripten has tons of LLVM optimizers under the hood). I think analyzing the startup time of texlive.js and looking for ways to speed it up would be a quicker (but maybe less interesting) way to achieve your goal

**Comment by aicioara** [comment]
@manuels That sounds interesting. I was only wondering why is texlive a couple of orders of magnitude slower than pdflatex? I was assuming this comes from converting low-level code into high-level code by making 1-to-1 mappings.

**Comment by jpallen** [comment]
The conversation isn't really any further forward than it was a few years ago. Still very R&D and idea-based, but nothing practical for ShareLaTeX on the horizon.

@aicioara I think it's very ambitious and I would caution you that there have been lots of rewrites of TeX started in many languages, but as far as I'm aware, none finished. I think the complexity of TeX is responsible for this, and the importance of exact TeX-accurate results in the rendering/execution. Basic TeX is easy, but TeX with all of it's idiosyncrasies is very very hard.

**Comment by manuels** [comment]
@aicioara, I inspected the performance of texlive.js a little bit more and it looks like one of the most obvious things that could be improved would be 'downloading' cached files:
When texlive.js wants to access a file, it asks the server for the latest version. Even if the browser has the lastest version (the server responds 'that's ok, use the version in your cache'), this back and forth costs about 100ms per file.
For 35 files in the demo, that's about 3.5sec (or 1/3 of the total runtime on my computer).

Now I have to think about how I could optimize this...

**Comment by aicioara** [comment]
@manuels That is really helpful, thank you. I might be working on this myself as well. Will let you know how it goes.
