### ISSUE TITLE
0.5.6 changelog

### ISSUE THREAD

**Issue by gianvito** [overleaf/overleaf#506]
Hi all, 
I have just noticed that the release 0.5.6 version of the docker has been released. Is there a changelog available? 

Moreover, is there a way to update the docker without re-installing the texlive full distro? 

Thank you

**Comment by moritzfl** [comment]
might be a bit late, but you can track version changes here as Release Notes are published and categorized for every 0.X version: https://github.com/sharelatex/sharelatex/wiki

**Comment by das7pad** [comment]
Hello,

Thanks for letting us know that the change log for 0.5.6 is missing. I'm sorry it took so long for us to get back to you! A lot has changed since 2017. We are maintaining complete release notes for our recent releases now.

You can find the release notes for the 5.x major version of Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises) in our wiki [here](https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x).

Greetings,
Jakob
