### ISSUE TITLE
Unable to compile with LuaLaTeX in 2.2.0

### ISSUE THREAD

**Issue by Roang-zero1** [overleaf/overleaf#695]
## Steps to Reproduce

1. Start an instance of Overleaf Community edition 2.2.0
2. Create a blank project
3. Switch the compiler to LuaLaTeX
4. Project failes to compile

## Expected Behaviour

Report should compile the Blank Project

## Observed Behaviour

The compilation fails with a very short log:
```
This is LuaTeX, Version 1.10.0 (TeX Live 2019)  (format=lualatex 2020.2.7)  17 FEB 2020 15:56
 restricted system commands enabled.
**main.tex

(/var/lib/sharelatex/data/compiles/5e4ab2fe174805007f361f60-5e2eeff3b0df9d019e5
06e98/main.tex
LaTeX2e <2020-02-02>
Lua module: luaotfload-main 2020-02-02 3.12 luaotfload entry point
Lua module: luaotfload-init 2020-02-02 3.12 luaotfload submodule / initializatio
n
Lua module: lualibs 2020-02-02 2.70 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2020-02-02 2.70 ConTeXt Lua libraries -- extended c
ollection.
Lua module: luaotfload-log 2020-02-02 3.12 luaotfload submodule / logging
```

## Context

I am currently unable to compile any of my LuaLaTeX based projects.

* All other compilers work nominal, only LuaLaTeX fails.

## Technical Info

* Sharelatex docker container does not work (with fresh install or after tlmgr update)
* Redis and MongoDB are filled with data
* https://github.com/jwilder/nginx-proxy with HTTPS is in use

* URL: internal system not available on the internet.
* Browser Name and version: Chrome  80.0.3987.87
* Operating System and version (desktop or mobile): Windows 10
* Signed in as:
* Project and/or file:

## Analysis

* Issuing a manual compile command on the docker container works as expected.
```bash
 cd /var/lib/sharelatex/data/compiles/<id>
 lualatex main.tex
```
* Issuing a manual latexmk command on the docker container works as expected.

**Comment by Roang-zero1** [comment]
The main.tex file has the following content:
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}

\title{Test}
\author{Lucas }
\date{February 2020}

\begin{document}

\maketitle

\section{Introduction}

\end{document}
```

**Comment by mserranom** [comment]
Confirmed it's not working in 2.2.x, compilation is OK in `2.0.x` and `2.1.x`.

**Comment by mserranom** [comment]
Recompiling from the UI produces the log indicated above. From `clsi.log`:

```
{"name":"clsi","hostname":"1781efcf06d2","pid":138,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9","compiler":"lualatex","timeout":180000,"mainFile":"main.tex","environment":{"CHKTEX_OPTIONS":"-nall -e9 -e10 -w15 -w16","CHKTEX_ULIMIT_OPTIONS":"-t 5 -v 64000"},"flags":[],"msg":"starting compile","time":"2020-02-18T09:53:50.764Z","v":0}

{"name":"clsi","hostname":"1781efcf06d2","pid":138,"level":30,"project_id":"5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9","command":["latexmk","-cd","-f","-jobname=output","-auxdir=/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9","-outdir=/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9","-synctex=1","-interaction=batchmode","-lualatex","/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9/main.tex"],"directory":"/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9","msg":"running command","time":"2020-02-18T09:53:50.764Z","v":0}
{"name":"clsi","hostname":"1781efcf06d2","pid":138,"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2020-02-18T09:53:50.765Z","v":0}

{"name":"clsi","hostname":"1781efcf06d2","pid":138,"level":30,"code":12,"signal":null,"project_id":"5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9","msg":"command exited","time":"2020-02-18T09:53:51.280Z","v":0}

{"name":"clsi","hostname":"1781efcf06d2","pid":138,"level":30,"project_id":"5e3ab31e99a9ce00982819ed","user_id":"5e3ab30499a9ce00982819e9","time_taken":517,"stats":{"latexmk-errors":1,"latex-runs":0,"latex-runs-with-errors":0,"latex-runs-0":1,"latex-runs-with-errors-0":1},"timings":{"cpu-percent":0,"cpu-time":0,"sys-time":0},"loadavg":[0.515625,1.69580078125,1.66796875],"msg":"done compile","time":"2020-02-18T09:53:51.281Z","v":0}
```

No actual error is produced, the `/compile` request returns 200.

Running the same `latexmk` command in the container:

```
$ CHKTEX_OPTIONS='-nall -e9 -e10 -w15 -w16'
$  CHKTEX_ULIMIT_OPTIONS='-t 5 -v 64000'
$ latexmk -cd -f -jobname=output -auxdir=/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9 -outdir=/var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9 -synctex=1 -interaction=batchmode -lualatex /var/lib/sharelatex/data/compiles/5e3ab31e99a9ce00982819ed-5e3ab30499a9ce00982819e9/main.tex
```
Running from the container produces an `output.pdf` file, and the log is complete: https://gist.github.com/mserranom/35cbb37c62ecb5985ed52e31ebeea7f9

**Comment by nubenum** [comment]
Confirming the findings so far, I investigated a bit more. I suspect it's related to the permission changes of overleaf/docker-image/pull/119 rather than to the node update. But I haven't found the actual issue.

[spawn.txt](https://github.com/overleaf/overleaf/files/4252279/spawn.txt) <-- in case it helps, the stdout of latexmk run by modified LocalCommandRunner.js with the -verbose -diagnostics flags:
```
"command":["latexmk","-cd","-f","-jobname=output","-auxdir=/var/lib/sharelatex/data/compiles/5a64e5bdda81e1013bc51301-5a143d73345a440079933f09","-outdir=/var/lib/sharelatex/data/compiles/5a64e5bdda81e1013bc51301-5a143d73345a440079933f09","-synctex=1","-interaction=batchmode","-verbose","-diagnostics","-lualatex","/var/lib/sharelatex/data/compiles/5a64e5bdda81e1013bc51301-5a143d73345a440079933f09/main.tex"]
```

I saw the "Removing no-longer-needed dependent ..." only ever when running from node, never when running from the command line. When running as www-data (`docker exec --user www-data`), another error occurred (after the first?): 
```
...
Rule classification: 
  Requested rules:
    lualatex
  No pre-primaries
  Primaries:
    lualatex
  No post-primaries
  No inner-level one_time rules, as expected
  No outer-level one_time rules
Make: doing pre_primary and primary...
  Make1 lualatex
Failure to make '/var/lib/sharelatex/data/compiles/5a64e5bdda81e1013bc51301-5a143d73345a440079933f09/output.pdf'
Rule classification: 
  Requested rules:
    lualatex
  No pre-primaries
  Primaries:
    lualatex
  No post-primaries
  No inner-level one_time rules, as expected
  No outer-level one_time rules
Latexmk: Errors, in force_mode: so I tried finishing targets
Collected error summary (may duplicate other messages):
  lualatex: failed to create output file
Latexmk: Undoing directory change
```

**Comment by Roang-zero1** [comment]
Any ETA when this will be fixed? This is a critical feature in our environment preventing us from applying the latest security fixes.

**Comment by nubenum** [comment]
Found the problem, it is the resurrection of #450. In the new image, the `/var/www/` directory is not writable for the www-data user anymore. This is due to [this change](https://github.com/overleaf/docker-image/pull/119/commits/e25d5593290705ad4167aa019863cb768afcd8b7#diff-0d6120519604dcbeadf1e4b5720766c1L29) removing the `chown` of this single directory from the init-scripts.

This is why the `/var/www/.texlive2019` can't be created automatically, which is why luatex tries to write its cache files to `/usr/local/texlive/2019/texmf-var`, where it has no permissions either.

A temporary workaround is giving the www-data user write permission to its own home directory:
`docker exec sharelatex chown www-data:www-data /var/www/`

**Comment by das7pad** [comment]
> Found the problem, it is the resurrection of #450. In the new image, the `/var/www/` directory is not writable for the www-data user anymore. This is due to [this change](https://github.com/overleaf/docker-image/pull/119/commits/e25d5593290705ad4167aa019863cb768afcd8b7#diff-0d6120519604dcbeadf1e4b5720766c1L29) removing the `chown` of this single directory from the init-scripts.
> 
> This is why the `/var/www/.texlive2019` can't be created automatically, which is why luatex tries to write its cache files to `/usr/local/texlive/2019/texmf-var`, where it has no permissions either.

Removing the ownership of application files for the (compiles) run user was intentional. I was not aware of anything writing into `/var/www`.

I see three options:
-  add `TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var` into the docker-compose file (backwards compatible for existing installations)
- add `ENV TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var` into the docker image (requires a new hotfix image)
- change the home directory of the `www-user` user to something writable e.g. `/var/lib/sharelatex/data` (requires a new hotfix image too)

**Comment by nubenum** [comment]
It's only the home directory that is chowned, this is non-recursive. Is this really a problem?

**Comment by das7pad** [comment]
A non-recursive ownership change is OK for `/var/www`. But this requires a new docker image, which may not be an option for some users.

**Comment by nubenum** [comment]
I'm not sure I understand. The issue was introduced by a change to the Docker image, so it can/should be fixed by a change to the Docker image, whether by chowning or by adding the ENV.
One can of course propose the change to the docker-compose as an alternative temporary workaround, until the new image version is available.

**Comment by jdleesmiller** [comment]
Thanks, everyone, for your comments.

> change to the docker-compose as an alternative temporary workaround

Yep, seems good as a workaround 👍 

> until the new image version is available

Yes, I think we should address this in the image for the next release. I'd lean toward setting `ENV TEXMFVAR` in the Dockerfile to somewhere writable rather than having the www-user home directory be writable, since that seems like a more explicit solution.

**Comment by nubenum** [comment]
Sounds good. I'll retract my pull request, since I can't adequately test such a change. I hope someone will have the time to make the fixes.

Thinking about the temporary workaround, please note that changing the docker-compose will lead to a recreation of the container, entailing about the same drawbacks for users as pulling a new image. Specifically, one will lose the texlive full installation, if one doesn't use a workaround like the one I proposed in #706. This is why I personally prefer the `docker exec sharelatex chown www-data:www-data /var/www/` workaround.

**Comment by Roang-zero1** [comment]
> add ENV TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var into the docker image (requires a new hotfix image)
I've modified our Dockerfile which is just based of off sharelatex with additional packages and lua modules, and after this change the Lua compilation is working again.
Unfortunately I don't have the time to test any further than that.

**Comment by TobiMiller** [comment]
@nubenum can you describe the steps to get a running full texlive with the standard docker-compose.yml? after each "docker-compose up" with one change in compose file everything is gone? even when i just change an ENV variable?

**Comment by das7pad** [comment]
I have put out https://github.com/overleaf/overleaf/pull/726 with the environment variable set in the docker-compose file.

Closing this for now.

**Comment by nubenum** [comment]
Mmh ok I don't really understand why you did it like this, since it will double the work for many users, and for yourself, if you then someday copy this very change over to the Dockerfile. But I suppose you had reasons. And at least, after so much time, there is an official "fix".
