### ISSUE TITLE
xkeyval.sty not found

### ISSUE THREAD

**Issue by zhengyima** [overleaf/overleaf#738]
i run the sharelatex with docker-compose, it runs well if i create and compile an example project. but when i upload a project that i can run well on overleaf.com, i get the following compiling error. i use the same compiler and comfigure as the online overleaf.com. 

anyone get the same error? help me!

```
LaTeX Error: File `xkeyval.sty' not found.

The compiler cannot find the file you want to include since it is a very very base macro. Make sure that you have uploaded the file and specified the file location correctly.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

```

i don't understand why this .sty cannot be found. i tried several methods, such as installing collection-latex with  tlmgr, but it cannot be solved. help!!!

**Comment by mujeeb2** [comment]
Initiative Q is an attempt by ex-PayPal guys to create a new payment system instead of payment cards that were designed in the 1950s. The system uses its own currency, the Q, and to get people to start using the system once it's ready they are allocating Qs for free to people that sign up now (the amount drops as more people join - so better to join early). Signing up is free and they only ask for your name and an email address. There's nothing to lose but if this payment system becomes a world leading payment method your Qs can be worth a lot. If you missed getting bitcoin seven years ago, you wouldn't want to miss this.
Here is my invite link: https://initiativeq.com/invite/b3YFOglAB
This link will stop working once I’m out of invites. Let me know after you registered, because I need to verify you on my end.

Sent from Yahoo Mail for iPhone


On Wednesday, May 20, 2020, 5:23 am, ZY Ma <notifications@github.com> wrote:




i run the sharelatex with docker-compose, it runs well if i create and compile an example project. but when i upload a project that i can run well on overleaf.com, i get the following compiling error. i use the same compiler and comfigure as the online overleaf.com.

anyone get the same error? help me!
LaTeX Error: File `xkeyval.sty' not found.

The compiler cannot find the file you want to include. Make sure that you have uploaded the file and specified the file location correctly.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)


i don't understand why this .sty cannot be found. i tried several methods, such as installing collection-latex with tlmgr, but it cannot be solved. help!!!

**Comment by mserranom** [comment]
Deleted and reported a comment due to spam.

**Comment by mserranom** [comment]
@zhengyima the compiler in Overleaf Community Edition is different than overleaf.com. It's expected that behaviour is not the same. Our commercial product, [Overleaf Server Pro](https://www.overleaf.com/for/enterprises), offers this compiler parity between overleaf.com and on-premise install.

In this case, it looks to me the package `xkeyval ` is missing from your installation.

**Comment by zhengyima** [comment]
i solve it based on this link [link](http://www.mamicode.com/info-detail-2959302.html)

in detail, i need to install scheme-full by tlmgr, which takes me a quite a lot time!!!

i wonder there is any other elegant solutions? 

Besides, the texlive should be updated to 2020 soon!!!  Or the tlmgr cannot install many packages strainghtly. @mserranom

**Comment by zhengyima** [comment]
> i solve it based on this link [link](http://www.mamicode.com/info-detail-2959302.html)
> 
> in detail, i need to install scheme-full by tlmgr, which takes me a quite a lot time!!!
> 
> i wonder there is any other elegant solutions?
> 
> Besides, the texlive should be updated to 2020 soon!!! Or the tlmgr cannot install many packages strainghtly. @mserranom

this issue saved my life!

**Comment by miladbohlouli** [comment]
You need to install a handful of the packages to resolve the problem. Refer to [this link.](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide)

**Comment by das7pad** [comment]
Hello,

I'm afraid we cannot offer LaTeX help for specific templates or packages in Overleaf Community Edition. Our Server Pro offering provides you with access to the same optimized LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live#About_Overleaf%E2%80%99s_upgrade_process) when preparing new TeXLive releases and generally make sure that templates either compile with the new version or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob
