### ISSUE TITLE
Getting started guide for new dev?

### ISSUE THREAD

**Issue by DanielTUK** [overleaf/overleaf#758]
Is there any information for a new developer to get started adjusting/improving sharelatex/overleaf? (I'd start with adjusting style and text. Adjusting code/logic would be a second step)

I managed to install overleaf ce using the official guide even though I have no experience with docker at all. I managed to change some small parts like updating texlive and adjusting styles of the webpages within the container. However these changes are reset whenever docker decides to rebuild the container (not sure what triggers this). I would therefore like to "install from source" to be able to make my changes persistent.

**Comment by mserranom** [comment]
I'm afraid there are currently no guidelines to setup a development environment for Overleaf Community Edition. 

A potential solution would involve the following:
 - Fork [`web`](https://github.com/overleaf/web) repo (or the service you want to update)
 - Update [`docker-compose.yml`](https://github.com/overleaf/overleaf/blob/master/docker-compose.yml) and mount the local `web/app` into `/var/www/sharelatex/web/app` inside the container.
 - Start Overleaf CE with `docker-compose up`
 - Edit your local fork code in `web/app` 
 - Restart `web` process. In order to do that you need to open bash in the `sharelatex` container, find the process pid with `ps -ef | grep web` and `kill` it. It will restart automatically.

Unfortunately this would only work with backend code, since frontend it's a bit more complex and needs to be built separately.

**Comment by mserranom** [comment]
We have launched a new development environment for Overleaf CE, please check it out. Any feedback is appreaciated!

https://github.com/overleaf/overleaf/tree/main/develop
