### ISSUE TITLE
Concurrent edits fail

### ISSUE THREAD

**Issue by lacraft** [overleaf/overleaf#887]
I have rewritten parts of ShareJsUpdateManajer.js to handle document updates using Automerge a CRDT library. The edits work properly when they are not concurrent. I can see all lines properly updated and propagated to all remote user sites. However, if they come in with the same update version number (meaning the edits take place concurrently) the edits update locally, but are not propagated to the other users and then the files become out of sync. Is there an event alert I am missing? Or some sort of timer delay? Thanks!

**Comment by das7pad** [comment]
Hello,

Thanks for opening this issue. There are many events that need to be handled to full integrate a different syncing backend with the Overleaf editor. Since 2021 we've replaced the Ace editor with Code Mirror 6, which has a different API. Moving away from share.js to a CRDT backend is not planned on our end. I'm afraid we cannot offer any coding assistance. You could take another look at all the interactions between the editor and share.js, and share.js with the connection here:
https://github.com/overleaf/overleaf/blob/main/services/web/frontend/js/features/source-editor/extensions/realtime.ts
https://github.com/overleaf/overleaf/blob/main/services/web/frontend/js/vendor/libs/sharejs.js

Greetings,
Jakob
